# Generated by Django 5.2.8 on 2025-11-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_brand_name_alter_category_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='brand_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='category_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('sku', ''), _negated=True), name='sku_not_empty'),
        ),
    ]
