# Generated by Django 5.2.8 on 2025-11-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_brand_brand_name_not_empty_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='sku_not_empty',
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('sku', ''), _negated=True), name='product_sku_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='product_title_not_empty'),
        ),
    ]
