# Generated by Django 5.2.8 on 2025-11-30 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='in_stock',
        ),
    ]
